//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavrentevMO_PC9_TestDemoEkz_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public Groups()
        {
            this.Students = new HashSet<Students>();
        }
    
        public int Group_Number { get; set; }
        public int Entrance_Year { get; set; }
    
        public virtual ICollection<Students> Students { get; set; }
    }
}
