//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavrentevMO_PC9_TestDemoEkz_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        public Subjects()
        {
            this.AttestationStudent = new HashSet<AttestationStudent>();
        }
    
        public string Subject_Name { get; set; }
        public string Attestation_Form { get; set; }
        public string FIO_Teacher { get; set; }
    
        public virtual ICollection<AttestationStudent> AttestationStudent { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
