//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavrentevMO_PC9_TestDemoEkz_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public Teachers()
        {
            this.Subjects = new HashSet<Subjects>();
        }
    
        public string Login { get; set; }
        public string FIO_Teacher { get; set; }
    
        public virtual ICollection<Subjects> Subjects { get; set; }
        public virtual Users Users { get; set; }
    }
}
